### ISSUE TITLE
check that all the examples using Direct Login are correct.

### ISSUE THREAD

**Issue by simonredfern** [OpenBankProject/Hello-OBP-DirectLogin-Python#3]
Check the example body is correct etc.

**Comment by wipxj3** [comment]
https://github.com/OpenBankProject/Hello-OBP-DirectLogin-Python/pull/2

Minor adjustments to make them work. 👍

**Comment by pbozin** [comment]
dl_username, dl_password and dl_consumer_key were removed from recent versions of OBP-API
